# ^^^ DEVELOPER NOTES ^^^
#
#
# YOU CAN GENERALIZE LIST VALUES. FOR EXAMPLE, ENTERING "MINECART" IN AN ENTITY BLOCK LIST WILL BLOCK ALL ENTITIES THAT CONTAIN THE WORD "MINECART"
# IN THEIR ENTITY TYPE NAME.
#
# The "block-in-factions" option is an extra step which will not perform any PTG tasks in Faction claims under any circumstance.
#
# The "state-override" option determines if actions such as explosives, placing, or break of existing locations where regeneration effects are scheduled will be allowed to merge.
# (For Example: When a player breaks a block and it is scheduled to regenerate, this will allow them to place block at that same location etc.)
#
# The "block-forming" option tells the plugin whether falling blocks created from physics can form on the ground
# upon impact or not (falling blocks spawned by the plugin).
#
# The "tree-physics" option will determine if the plugin will take control over trees and perform its magic.
#
# The "tree-regeneration" option determines if a block part of the tree physics will regenerate after a delay with a speed.
#
# The "tree-regeneration-speed" option is the integer (IN TICKS, 20 ticks = 1 second) that the tree regeneration process will use
# as its speed. The longer the duration, the longer the time in between block regeneration forming a more block-by-block design.
#
# The "tree-regeneration-speed" option is the integer (IN TICKS, 20 ticks = 1 second) that the tree regeneration process will WAIT
# before starting the regeneration process.
#
# The "tree-animation" option determines if the plugin will animation the action by spawning falling blocks.
#
# The "tree-gravity-effect" option determines if the animation will look fancy or not (falling blocks last longer and "tree-animation" must be enabled).
#
# The "tree-drops" option determines if the tree's blocks will break normally and drop stuff or not.
#
# The "no-entity-explosions" determines if the plugin will block all entity explosion damage to blocks or not.
#
# The "explosive-regeneration" option determines if a block damaged by an explosive will regenerate after a delay with a speed.
#
# The "explosive-regeneration-speed" option is the integer (IN TICKS, 20 ticks = 1 second) that the explosive regeneration process will use
# as its speed. The longer the duration, the longer the time in between block regeneration forming a more block-by-block design.
#
# The "explosive-regeneration-speed" option is the integer (IN TICKS, 20 ticks = 1 second) that the explosive regeneration process will WAIT
# before starting the regeneration process.
#
# The "explosive-physics" option tells the plugin whether or not to spawn falling blocks as a form of decoration from explosions.
#
# The "explosive-drops" option determines whether exploded blocks have drops or not.
#
# The "explosive-tnt-ignite" option tells the plugin if tnt harmed by an entity explosion should be ignited, rather than taking the effect
# of other normal blocks.
#
# The "explosive-tnt-fuse" option tells the plugin what the fuse of harmed tnt blocks should be (IN TICKS, 20 ticks = 1 second). This
# option requires the "explosive-tnt-ignite" feature to be enabled.
#
# The "blocked-entity-regeneration" is a list that will prevent explosive block regeneration entirely if the explosion was caused by an entity in this list.
#
# The "explosive-blocked-entities" is a list that will block explosive damage and effects toward all entity types found in the list.
#
# The "place-removal" option determines if block placed by the player will regenerate after a delay.
#
# The "place-removal-delay" option determines how long (IN TICKS, 20 ticks = 1 second) it will take for the block to be removed and reverted to the original material.
#
# The "place-only-effected" list will act as a whitelist when the "place-removal" option is enabled and will ONLY remove the materials found in the list.
# (NOTE: This list will be avoided if it is empty.)
#
# The "break-regeneration" option determines if block broken by the player will regenerate after a delay.
#
# The "break-drops" option determines if blocks broken by the player drop items or not.
#
# The "break-regeneration-delay" option determines how long (IN TICKS, 20 ticks = 1 second) it will take for the block to be regenerated
# to its original state.
#
# The "break-only-effected" list will act as a whitelist when the "break-regeneration" option is enabled. All materials in the list will regenerate after a
# delay to their original material. (NOTE: This list will be avoided if it is empty.)
#
# The "world-blacklist" list will block all PTG actions in the defined worlds.
#
# The "avoided-materials" list should contain all materials that should be avoided like the black plague. Essentially these materials
# are safe from the plugins actions at all costs.
#

block-in-factions: false
state-override: false
block-forming: false

tree-physics: true
tree-regeneration: true
tree-regeneration-speed: 2
tree-regeneration-delay: 300
tree-animation: true
tree-gravity-effect: true
tree-drops: true
tree-replant: true

no-entity-explosions: false
explosive-regeneration: true
explosive-regeneration-speed: 5
explosive-regeneration-delay: 20
explosive-physics: true
explosive-drops: true
explosive-tnt-ignite: true
explosive-tnt-fuse: 10
blocked-entity-regeneration: []
explosive-blocked-entities:
  - "ARMOR_STAND"
  - "PAINTING"
  - "ITEM_FRAME"
  - "MINECART"

place-removal: true
place-removal-delay: 20
place-only-effected:
  - "TORCH"

break-regeneration: true
break-drops: true
break-regeneration-delay: 20
break-only-effected:
  - "ORE"

world-blacklist: []
avoided-materials:
  - "BEDROCK"
  - "OBSIDIAN"